//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_movement_hand : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.movement_hand_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveForward
        {
            get
            {
                return SteamVR_Actions.movement_hand_MoveForward;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveBackwards
        {
            get
            {
                return SteamVR_Actions.movement_hand_MoveBackwards;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveLeft
        {
            get
            {
                return SteamVR_Actions.movement_hand_MoveLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveRight
        {
            get
            {
                return SteamVR_Actions.movement_hand_MoveRight;
            }
        }
    }
}
