//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_non_dominant_hand : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Crouch
        {
            get
            {
                return SteamVR_Actions.non_dominant_hand_Crouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.non_dominant_hand_Menu;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MenuDirection
        {
            get
            {
                return SteamVR_Actions.non_dominant_hand_MenuDirection;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuUp
        {
            get
            {
                return SteamVR_Actions.non_dominant_hand_MenuUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuDown
        {
            get
            {
                return SteamVR_Actions.non_dominant_hand_MenuDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuLeft
        {
            get
            {
                return SteamVR_Actions.non_dominant_hand_MenuLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuRight
        {
            get
            {
                return SteamVR_Actions.non_dominant_hand_MenuRight;
            }
        }
    }
}
