//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_menu : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean MenuUp
        {
            get
            {
                return SteamVR_Actions.menu_MenuUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuDown
        {
            get
            {
                return SteamVR_Actions.menu_MenuDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuLeft
        {
            get
            {
                return SteamVR_Actions.menu_MenuLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuRight
        {
            get
            {
                return SteamVR_Actions.menu_MenuRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuTabLeft
        {
            get
            {
                return SteamVR_Actions.menu_MenuTabLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuTabRight
        {
            get
            {
                return SteamVR_Actions.menu_MenuTabRight;
            }
        }
    }
}
