//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_dominant_hand : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Interact
        {
            get
            {
                return SteamVR_Actions.dominant_hand_Interact;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuTabRight
        {
            get
            {
                return SteamVR_Actions.dominant_hand_MenuTabRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuTabLeft
        {
            get
            {
                return SteamVR_Actions.dominant_hand_MenuTabLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuInteract
        {
            get
            {
                return SteamVR_Actions.dominant_hand_MenuInteract;
            }
        }
    }
}
